"""create initial table

Revision ID: 001
Revises: 
Create Date: 2026-07-13 23:14:15.767522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.BigInteger(), nullable=False),
    sa.Column('exeName', sa.String(length=255), nullable=False),
    sa.Column('fileDescription', sa.String(length=512), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('allPaths', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deviceUser',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.BigInteger(), nullable=False),
    sa.Column('deviceID', sa.String(length=64), nullable=False),
    sa.Column('osUsername', sa.String(length=255), nullable=False),
    sa.Column('deviceName', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.BigInteger(), nullable=False),
    sa.Column('deviceUserID', sa.Integer(), nullable=False),
    sa.Column('appID', sa.Integer(), nullable=False),
    sa.Column('startTime', sa.BigInteger(), nullable=False),
    sa.Column('endTime', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('events')
    op.drop_table('deviceUser')
    op.drop_table('applications')
    # ### end Alembic commands ###
