"""add app limits and downtime tables

Revision ID: 002
Revises: 001
Create Date: 2026-07-16 22:52:25.145442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appLimits',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.BigInteger(), nullable=False),
    sa.Column('updatedAt', sa.BigInteger(), nullable=False),
    sa.Column('deviceUserID', sa.Integer(), nullable=False),
    sa.Column('appID', sa.Integer(), nullable=False),
    sa.Column('dailyLimitMinutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('downtime',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.BigInteger(), nullable=False),
    sa.Column('updatedAt', sa.BigInteger(), nullable=False),
    sa.Column('deviceUserID', sa.Integer(), nullable=False),
    sa.Column('startMinute', sa.Integer(), nullable=False),
    sa.Column('endMinute', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('downtime')
    op.drop_table('appLimits')
    # ### end Alembic commands ###
