"""add website events table

Revision ID: 004
Revises: 003
Create Date: 2026-07-17 18:35:56.167215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('websiteEvents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdAt', sa.BigInteger(), nullable=False),
    sa.Column('deviceUserID', sa.Integer(), nullable=False),
    sa.Column('startTime', sa.BigInteger(), nullable=False),
    sa.Column('endTime', sa.BigInteger(), nullable=False),
    sa.Column('tabUrl', sa.Text(), nullable=False),
    sa.Column('tabTitle', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('websiteEvents')
    # ### end Alembic commands ###
